[general]

[interface]
# Text when no input present.
place_holder = ""
suggestion_lines = 999

[[modules]]
description = "power menu"
prefix = "po"
cmd = """
function power {
if [[ -n $1 ]]; then
case $1 in
"shutdown") systemctl poweroff ;;
"reboot") systemctl reboot ;;
"suspend") systemctl suspend ;;
"hibernate") systemctl hibernate ;;
esac fi }
power $(echo -e 'shutdown\nreboot\nsuspend\nhibernate' | fzf --reverse --padding 1,2 --info-command 'printf " power menu ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter " " --pointer " ▌" --color "bg+:-1,pointer:1,info:8,separator:8,scrollbar:0" --prompt '  ' | tail -1)
"""

[[modules]]
description = "Application Picker"
prefix = "app"
cmd = "fsel"

[[modules]]
description = "Wifi Managment"
prefix = "wifi"
cmd = "foot --app-id=otter-launcher --window-size-pixels=2540x1420 --override=colors.alpha=0.9 impala"
unbind_proc = true

[[modules]]
description = "Sound Managment"
prefix = "vol"
cmd = "wiremix --tab=output"

[[modules]]
description = "Open Directory"
prefix = "cd"
cmd = """
find $HOME -type d -not -path '*/.cache/*' 2>/dev/null | fzf --reverse --padding 1,3 --info-command 'printf " directories ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter ' ' --pointer ' ▌' --color 'bg+:-1,pointer:1,info:8,separator:8,scrollbar:0' --prompt '  ' | xargs -r -I [] setsid -f "$(echo $TERM | sed 's/xterm-//g')" -e yazi '[]'
"""

[[modules]]
description = "Find Files"
prefix = "ff"
cmd = """
find $HOME -type f -not -path '*/.cache/*' 2>/dev/null | fzf --reverse --padding 1,3 --info-command 'printf " files ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter ' ' --pointer ' ▌' --color 'bg+:-1,pointer:1,info:8,separator:8,scrollbar:0' --prompt '  ' | setsid -f xargs -r -I [] xdg-open '[]'
"""
